### PR TITLE
Export revdep_report()

### PR DESCRIPTION
**Pull request by lionel-**
Got burn by calling the unexported function `revdep_report()` in the middle of a revdep run ;). This PR extracts the safe part of `revdep_report()` into an exported function that will not alter the revdep state.

(In case someone else closes the current revdep session impromptly, you can restore the current run by running `revdepcheck:::db_metadata_set(pkg_path, "todo", "run")`)

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! Can we just do this in the original function, maybe with a warning if the results are partial? Just to keep the API smaller, if it makes sense.

**Comment by lionel-** [comment]
I'm not sure I understand. The original function is not exported and automatically called when revdepchecks are complete.

**Comment by gaborcsardi** [comment]
We can just export it then. 

Btw. there is also `revdep_summary()` and `revdep_details()`, aren't those enough for early inspection. TBH I am not sure if the DB is always in a consistent state for a report.

**Comment by lionel-** [comment]
We can't export the original function because it changes the state of the revdep loop. Would you like to rename `revdep_report_partial()` to `revdep_report()`? I think it's better to be explicit that the results won't be complete.

> Btw. there is also revdep_summary() and revdep_details(), aren't those enough for early inspection.

It isn't as practical when you're inspecting a large number of revdeps.

> TBH I am not sure if the DB is always in a consistent state for a report.

Good point about the db state, I haven't encountered any problem when I've used it but I'll filter out rows that don't have both `old` and `new` fields completed. Probably should do it in `db_results()` before comparison.

**Comment by gaborcsardi** [comment]
>  I think it's better to be explicit that the results won't be complete.

OK, got it.

>  I'll filter out rows that don't have both old and new fields completed.

Good idea.

Can you also add a note to the report, at the top, that says that it is a partial report? Thanks.

**Comment by lionel-** [comment]
Can you check again please? I have changed the approach and the exported function is now `revdep_report()`, it checks that the state is `"done"` and if not adds a partial note and signals a message.

I will take care of filtering incomplete results after we have merged the DB refactor PR.

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
