### PR TITLE
Consider \\. to be part of package name.

### PR DESCRIPTION
**Pull request by joethorley**
Previously dependencies of leaflet.extras were being included (extras only has 4 depedencies)
``` r
revdepcheck::cran_revdeps("extras", "Imports")
#>  [1] "animaltracker" "bcdata"        "GPSeqClus"     "gwavr"        
#>  [5] "IceSat2R"      "mapedit"       "mcmcderive"    "mcmcr"        
#>  [9] "MDMAPR"        "naturaList"    "nlist"         "oceanis"      
#> [13] "term"          "wallace"
```

<sup>Created on 2022-10-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Now with this pull request the correct 4 dependencies are returned
``` r
revdepcheck::cran_revdeps("extras", "Imports")
#> [1] "mcmcderive" "mcmcr"      "nlist"      "term"
```

<sup>Created on 2022-10-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by hadley** [comment]
I think we need a bit more than this because `leaflet.extras` would also match ` leafletXextras` etc (not very likely,  but a suggestion that we shouldn't be using regexps here).

**Comment by hadley** [comment]
@gaborcsardi do you think we could switch to `tools::dependsOnPkgs(package, dependencies = dependencies, installed = allpkgs, recursive = FALSE)` here?

**Comment by gaborcsardi** [comment]
We have now better tools for this, we could start using them, e.g. `pkgcache::meta_cache_revdeps()`.

**Comment by hadley** [comment]
Maybe that's at the root of some of the strangeness in #319

**Comment by hadley** [comment]
Hmmm, but I can't get them to line up:

``` r
pkgcache <- pkgcache::meta_cache_revdeps("tidyr", dependencies = TRUE, recursive = FALSE)$package
#> ℹ Loading metadata database
#> ✔ Loading metadata database ... done
#> 
length(pkgcache)
#> [1] 4087
revdepcheck <- revdepcheck::cran_revdeps("tidyr")
length(revdepcheck)
#> [1] 1750
```

<sup>Created on 2023-01-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gaborcsardi** [comment]
pkgcache includes binaries and sources separately, and by default includes bioc as well. It is something like this:

```r
cache <- pkgcache::cranlike_metadata_cache$new(platforms = "source", bioc = FALSE)
revdeps <- cache$revdeps("tidyr", dependencies = TRUE, recursive = FALSE)
revdeps[c("package", "version")]
```

**Comment by gaborcsardi** [comment]
We should probably also specify `repos` in `cranlike_metadata_cache$new()`, to avoid people's custom repos, and only use CRAN.

**Comment by hadley** [comment]
Ah, yeah, in parallel I realised that `cran_revdeps()` depends on `getOption("repos")` which seems bad.

**Comment by gaborcsardi** [comment]
I am fairly sure that it is OK, it uses its own `get_repos()` which is more careful.

**Comment by hadley** [comment]
Not really: https://github.com/lbergelson/revdepcheck/blob/patch-1/R/deps.R#L35-L36

**Comment by gaborcsardi** [comment]
> Not really: [lbergelson/revdepcheck@patch-1/R/deps.R#L35-L36](https://github.com/lbergelson/revdepcheck/blob/patch-1/R/deps.R?rgh-link-date=2023-01-24T14%3A45%3A00Z#L35-L36)

I am not sure what you mean, sorry. Is that fork relevant, or that's just accidental?

**Comment by hadley** [comment]
Ooops, accidental. Anyway, I'm going to close this PR and open a new one that uses pkgcache.

**Pull request closed without merging**
