### PR TITLE
Cloud reporting tweaks

### PR DESCRIPTION
**Pull request by hadley**
* Only write failures if requested
* Write CRAN comments too

### CODE REVIEW

**Comment by jimhester** [comment]
It seems dangerous to have this be false by default

**Comment by hadley** [comment]
Why do you think it's dangerous? You can still easily get the information, and it's still displayed in the `README.md`. I find it frustrating because for testhat it's generating an extremely large file (>10 meg) and takes forever to finish.

**Comment by hadley** [comment]
@jimhester changed the default to `TRUE` since I don't care that much and this unblocks me for testthat.

**Comment by jimhester** [comment]
Because then it is very easy to miss that there are failures, and at least sometimes these failures are real issues that should be addressed.

**Pull request merged**
