### PR TITLE
New warm_cache = FALSE argument to revdep_check()

### LINKED ISSUE #33: Install all deps of revdeps first?
I think there are two advantages:

* crancache will have maximal information, so can easily use parallel downloads etc
* you're more robust to bad internet (i.e. #15)

You'd still do the install phase for each package to create the individual libraries, and to possible catch new updates in long running rev dep processes.

### PR DESCRIPTION
**Pull request by krlmlr**
Closes #33.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
While this has some good parts, I think we can do better. In particular, the installation of the dependencies is not parallelized here, while it was originally (with the caveat of likely extra work because of installing/compiling the same package multiple times). So in some cases this solution can be slower, actually.

The other thing is that I don't want to create a `warm_cache` option. For the user it is really not trivial to decide whether to warm the cache or not. Ideally we should not have this option. Maybe it should be just set to `TRUE` automatically for platforms that need compilation, and `FALSE` otherwise.

Here is an alternative solution:
* We do order the dependencies topologically, and this will also include the revdep-checked packages as well. 
* We actually use the whole dependency tree, not just the topological order. 
* We run each installation in its own process, in the "correct" order.
* As soon as a revdep checked packages has all of its dependencies in place (i.e. in the cache), we start checking it.

What do you think?

**Comment by krlmlr** [comment]
Thanks for your review. This is in a "works for me" state right now. I'm sure we can do better, but I can't allocate more time to this problem at this point.

How about merging the first two commits and #52, and take a new stab on warming vs. fully parallel installation vs. ... later? It would help if we had a dependency-aware scheduler at our disposal; revdepcheck currently implements something along these lines, but a generic scheduler would be very useful in other contexts like remake, and hence better suited in a separate package. (Or do you happen to have one ready? I wouldn't be surprised ;-) )

**Comment by gaborcsardi** [comment]
OK, if you could just remove the `warm_cache` argument from the function, and set it automatically to `TRUE` on Linux, and `FALSE` on other platforms, that should work. Then I can merge it.

Plus, can you add a message to the screen if the cache is warming up. (That's the other thing that I don't like that much, that warming up the cache can take (very) long, and there is no communication to the user about what it happening, and there is no ETA, either.

**Comment by krlmlr** [comment]
We could add an approximate ETA (because installation happens in chunks of 10), and the installation is verbose so there's more output than you likely want. But I also want to run `warm_cache = FALSE` most of the time on Linux, because it still takes time even if all binary packages are there.

Currently there seems to be no easy way to run parts of `revdep_check()`. For instance, I haven't found a way to revdep-check only two known packages without prior results available. I'd rather work on further modularizing the code and then provide an entry point for warming the cache, so I can have a "manual" setup with optionally running the warm-up. Would that work?

**Comment by gaborcsardi** [comment]
> We could add an approximate ETA (because installation happens in chunks of 10), and the installation is verbose so there's more output than you likely want.

But that ETA will be way off wrt the total `revdepcheck` running time.

> But I also want to run warm_cache = FALSE most of the time on Linux, because it still takes time even if all binary packages are there.

This is just another argument for *not* having this feature, or making it automatic. :)

> Currently there seems to be no easy way to run parts of revdep_check(). 

Look at the `revdep_add` function.

**Comment by gaborcsardi** [comment]
> ... and the installation is verbose so there's more output than you likely want.

Oh, yeah, that's not great.

**Comment by gaborcsardi** [comment]
@krlmlr So there is no easy heuristic to set `warm_cache` automatically?

Btw. why does it take long if the binaries are available? Because of the installs or the dependency lookup?

**Comment by krlmlr** [comment]
Installing a binary package is fast, but still not instantaneous. Maybe if crancache had a way of only downloading the binary package, it would be faster. FWIW, a lot of time during warmup is spent with `gzip -d`. 

I'll be looking into remake soon, I'll think about a task queue for R with R, which then could be used to improve package installation. Are there existing solutions we could build upon?

I don't really like the cache warmup either. I'd still use it because it offers somewhat better control over the installation process.

**Comment by gaborcsardi** [comment]
> Installing a binary package is fast, but still not instantaneous. Maybe if crancache had a way of only downloading the binary package, it would be faster. FWIW, a lot of time during warmup is spent with gzip -d.

If `gzip -d ` is the bottleneck, that's pretty good, actually. 

> I'll be looking into remake soon, I'll think about a task queue for R with R, which then could be used to improve package installation. Are there existing solutions we could build upon?

I don't want to use `remake` for this, it is not needed. I think the solution that I outlined above is not so hard to implement (for me, since I am familiar with the event loop). I'll try to implement that soon.

> I don't really like the cache warmup either. I'd still use it because it offers somewhat better control over the installation process.

Yeah, but we can just make the install process "optimal". :)

**Comment by gaborcsardi** [comment]
As for queueing solutions, I actually wrote `liteq` for `revdepcheck`, but then ended up not using it.

**Comment by krlmlr** [comment]
Yes, I completely forgot about that. Why did you decide against it?

**Comment by gaborcsardi** [comment]
It was just not needed. The event loop in `revdepcheck` can take of the scheduling, and it can also collect the output and the error. At this point, a queue was just further complication without much benefit. 

It would probably have meant an extra R process per check as well, but this is a minor issue.

**Comment by krlmlr** [comment]
Thanks for clarifying. Happy to review your extension that takes care of installing the dependencies once and on time. #52 contains code that may be useful for this.

**Comment by krlmlr** [comment]
One more thing: I think we should also have a "library cache" and use symlinks/junction points into that cache instead of installing the packages multiple times. This would be in addition to the crancache, and fairly easy to achieve if you really split up the installation into tasks.

**Comment by gaborcsardi** [comment]
I am not sure if we want symlinks. Binary packages should be fast enough, that's just uncompressing:
```r
❯ system.time(crancache::install_packages(c("pkgconfig", "purrr", "remotes", "RSQLite", "crayon", "dplyr", "tibble")))
Installing packages into ‘/Users/gaborcsardi/r_pkgs’
(as ‘lib’ is unspecified)

The downloaded binary packages are in
	/var/folders/ws/7rmdm_cn2pd8l1c3lqyycv0c0000gn/T//RtmpG8VlL5/downloaded_packages
   user  system elapsed
  2.203   0.217   2.450
```

I think a couple of seconds per revdep check is completely fine.

**Comment by krlmlr** [comment]
Think about BH or those 700 MB beasts from Bioconductor. But I agree this isn't top prio.

**Comment by gaborcsardi** [comment]
OK, `BH` is ~ 5sec, but that's an exception. I would also not keep an installed version of `BH` in the cache, because it is just too big.

Maybe we could have sg. just for the time of the `revdepcheck` run, but I agree that this is not top priority currently.

**Comment by gaborcsardi** [comment]
Actually, maybe it is not the uncompress time that is dominant, because this is also ~5sec:
```r
❯ system.time(crancache::install_packages(c("pkgconfig", "purrr", "remotes", "RSQLite", "crayon", "dplyr", "tibble", "BH")))
Installing packages into ‘/Users/gaborcsardi/r_pkgs’
(as ‘lib’ is unspecified)

The downloaded binary packages are in
	/var/folders/ws/7rmdm_cn2pd8l1c3lqyycv0c0000gn/T//RtmpG8VlL5/downloaded_packages
   user  system elapsed
  2.604   2.096   4.881
```

**Comment by gaborcsardi** [comment]
Yeah, the `available.packages` calls dominate, and the actual installation is less than a second.

**Comment by krlmlr** [comment]
Maybe parallel installation belongs in the remotes package?

**Comment by bbolker** [comment]
just wanted to point out that I might be willing to keep a copy of BH in the cache, if it's a choice between that and recompiling it every time ...

**Comment by gaborcsardi** [comment]
> just wanted to point out that I might be willing to keep a copy of BH in the cache, if it's a choice between that and recompiling it every time ...

I am not sure what you mean. All packages are cached and built only once. 

(Well, currently this is not strictly true, there are exceptions sometimes, but this is the goal.)

**Comment by gaborcsardi** [comment]
> Maybe parallel installation belongs in the remotes package?

Yes, it does. I am working on this right now, coming soon. Teaser: it is going to be awesome. :)

**Comment by krlmlr** [comment]
Obsolete. (Yes, package installation is awesome now!)

**Comment by krlmlr** [comment]
Let's add this option.

**Pull request closed without merging**
