### PR TITLE
memoise available_packages()

### PR DESCRIPTION
**Pull request by krlmlr**
Makes the event loop much much smoother, but still not sufficient for 64 cores. I suspect in this scenario many workers are working on building/installing the same packages, also I/O queues might overflow.

Maybe it's also just the effort of reinstalling BH all over again.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
I agree that this is probably a Linux issue, because you are building the same packages from source in multiple workers, and maybe this generates too much output. 

I don't understand why you would install BH many times, though, is it a reverse dependency?

Unfortunately memoising is not the correct solution here, because over a long change the package metadata database will change, and this leads to very annoying errors. (We saw these before.)

`pkgdepends` uses a better approach. It can use the same metadata for all operations, and it can download CRAN packages from `Archive`. It also has an in-memory cache. I will just port that approach over here for now. Eventually `revdepcheck` will use `pkgdepends` directly.

**Comment by krlmlr** [comment]
Maybe we can make memoization dependent on a file timestamp/hash?

**Comment by krlmlr** [comment]
```
$ wget --server-response --spider https://cran.r-project.org/src/contrib/PACKAGES.rds
Spider mode enabled. Check if remote file exists.
--2017-11-13 15:04:43--  https://cran.r-project.org/src/contrib/PACKAGES.rds
Resolving cran.r-project.org (cran.r-project.org)... 137.208.57.37
Connecting to cran.r-project.org (cran.r-project.org)|137.208.57.37|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Date: Mon, 13 Nov 2017 14:04:47 GMT
  Server: Apache/2.4.10 (Debian)
  Last-Modified: Mon, 13 Nov 2017 12:55:51 GMT
  ETag: "42cf8-55ddcca45c08d"
  Accept-Ranges: bytes
  Content-Length: 273656
  Keep-Alive: timeout=15, max=100
  Connection: Keep-Alive
Length: 273656 (267K)
Remote file exists and could contain further links,
but recursion is disabled -- not retrieving.
```

Takes ~0.25s on my machine. But that looks like a lot of effort.

Maybe permit local CRAN and BioConductor mirrors?

BH seems to be a dependency to many packages I'm testing, but I'm not sure yet.

**Comment by krlmlr** [comment]
BH is used by 233 of 262 of tibble's reverse dependencies.

**Comment by gaborcsardi** [comment]
Ouch.

**Comment by krlmlr** [comment]
Awaiting your solution that downloads from `Archives`.

**Pull request closed without merging**
