### PR TITLE
Make get_repos(bioc = TRUE) respect option 'repos' (Fixes #119)

### LINKED ISSUE #119: revdepcheck:::get_repos(bioc = TRUE) doesn't respect what's in getOption("repos")
# Issue
`revdepcheck:::get_repos(bioc = TRUE)` prepends built-in Bioconductor URLs to any existing Bioconductor URLs already specified in `getOption("repos")`.   There are two problems with this:

1. Since it _prepends_ the built-in URLs, they will have higher priority than the ones specified in the `repos` option.
2. The built-in URLs are online repositories and because `revdepcheck` uses `options(warn = 2)` when installing packages, it will throw an error if those fail/cannot be accessed, e.g. due to lack of internet access.  Thus, it prevents using `revdepcheck` in offline mode.

# Example
With:
```r
> getOption("repos")
                                                                      CRAN 
                            "file:///netapp/home/hb/shared/r-mirrors/cran" 
                                                                  BioCsoft 
           "file:///netapp/home/hb/shared/r-mirrors/bioconductor/3.6/bioc" 
                                                                   BioCann 
"file:///netapp/home/hb/shared/r-mirrors/bioconductor/3.6/data/annotation" 
                                                                   BioCexp 
"file:///netapp/home/hb/shared/r-mirrors/bioconductor/3.6/data/experiment" 
```
we get:
```r
> repos <- revdepcheck:::get_repos(bioc = FALSE)
> repos
                                                                      CRAN 
                            "file:///netapp/home/hb/shared/r-mirrors/cran" 
                                                                  BioCsoft 
           "file:///netapp/home/hb/shared/r-mirrors/bioconductor/3.6/bioc" 
                                                                   BioCann 
"file:///netapp/home/hb/shared/r-mirrors/bioconductor/3.6/data/annotation" 
                                                                   BioCexp 
"file:///netapp/home/hb/shared/r-mirrors/bioconductor/3.6/data/experiment" 
```

So far so good, but:
```r
> repos <- revdepcheck:::get_repos(bioc = TRUE)
> repos
                                                                  BioCsoft 
                              "https://bioconductor.org/packages/3.5/bioc" 
                                                                   BioCann 
                   "https://bioconductor.org/packages/3.5/data/annotation" 
                                                                   BioCexp 
                   "https://bioconductor.org/packages/3.5/data/experiment" 
                                                                 BioCextra 
                             "https://bioconductor.org/packages/3.5/extra" 
                                                                      CRAN 
                            "file:///netapp/home/hb/shared/r-mirrors/cran" 
                                                                  BioCsoft 
           "file:///netapp/home/hb/shared/r-mirrors/bioconductor/3.6/bioc"
                                                                   BioCann 
"file:///netapp/home/hb/shared/r-mirrors/bioconductor/3.6/data/annotation" 
                                                                   BioCexp 
"file:///netapp/home/hb/shared/r-mirrors/bioconductor/3.6/data/experiment" 
```

PS. The `BioCextra` URL has been dropped in Bioconductor >= 3.6 (meaning it will also produce an error due to `warn = 2`).

# Patch
I'm happy to submit a PR that will make `revdepcheck:::get_repos(bioc = TRUE)` add only `BioC*` entries that are missing from `repos`.  I've got a fix ready locally.

### PR DESCRIPTION
**Pull request by HenrikBengtsson**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! Looks good, but something is wrong with your branch, I cannot rebase/merge it on GitHub. Anyway, I'll merge it manually.

**Comment by HenrikBengtsson** [comment]
Yeah, I saw that I was on an slightly outdated version and then I merged your master afterward.  Maybe that what messed it up.  Thxs fixing this.

**Comment by gaborcsardi** [comment]
Yeah, in general it is better to rebase then merge, for PRs.

**Comment by gaborcsardi** [comment]
Merged manually: b0de04096b5037412f3c7368c328f51c0c394b61

**Pull request closed without merging**
