### PR TITLE
Add cran parameter (#333 and #340 candidate fix)

### PR DESCRIPTION
**Pull request by maksymiuks**
@gaborcsardi  This is a candidate fix for #333

I've realized that fixing the issue reported above is dead simple. In my opinion `get_repos()` helper should append CRAN to repos only conditionally on some input parameter, rather than every time CRAN is not found in current options. Therefore I've just added this parameter and propagated it upstream including `revdep_check()` and documentation.

### CODE REVIEW

**Comment by maksymiuks** [comment]
Requesting review @gaborcsardi

**Comment by maksymiuks** [comment]
@gaborcsardi Are there any chance to address this in the nearest future?

**Comment by maksymiuks** [comment]
Added candidate fix for #340

**Comment by gaborcsardi** [comment]
Thanks and sorry for the super long wait!

**Pull request merged**
